### ISSUE TITLE
React Native does not have a built-in secure random generator

### ISSUE THREAD

**Issue by p4kaidu** [Autodesk/clearx#8] opened 2019-12-21 17:03 UTC
**Describe the bug**
I get an error when using with React Native

**To Reproduce**
1. Create store
`
const AppStore = new ClearX({
    user:{
        nick:null,
        email:null,
        phone:null,
        isActivate:false,
    },
    map:{
        marks:[]
    }
});
`
2. Run app

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/45810834/71311030-6af7b100-242c-11ea-8951-ca07f47b6c27.png)

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android 9
 - Version RN 0.61.5 

**Additional context**
Can a library work with React Native?

**Comment by svapreddy** [comment] 2019-12-21 17:34
@p4kaidu Thanks for bringing it our notice. We published a new version with the fix. Here you can check it's working with React Native: https://codesandbox.io/s/wonderful-ardinghelli-217sk

**Comment by svapreddy** [comment] 2019-12-22 02:57
Closing the issue. Please let us know if the issue isn’t fixed for you. The link above demonstrates the usage with React Native.

**Closed by svapreddy** 2019-12-22 02:57 UTC
